Adds auto-generated documentation from JSON Schemas
RockefellerArchiveCenter/rac_schemas pull request #38
Opened 2021-02-18 15:46 UTC by p-galligan

Adds HTML documentation of the JSON schemas, as well as a script to generate that documentation from JSON files.

2021-02-18 19:00 UTC, helrond requested changes
OK I've added some specific comments in here, but I think we also need to add a `Documentation` section to the README which describes how to generate docs (and the necessary dependencies).

2021-02-18 19:00 UTC, helrond commented on generate_docs.py
> +    '''Generates HTML documentation based on JSON schema files.'''
Double quotes in docstrings plz!

2021-02-18 19:00 UTC, helrond commented on generate_docs.py
> +    help="Directory to write HTML files to.")
Wondering if we can provide default values for these args, so the script without having to worry about input/output dirs?

2021-02-18 19:00 UTC, helrond commented on generate_docs.py
> +            if file.endswith(".json"):
You could do this in a single line using list comprehension.

2021-02-22 16:44 UTC, p-galligan commented on generate_docs.py
> +            if file.endswith(".json"):
Should be done now!

2021-02-22 18:28 UTC, helrond approved these changes

2021-02-22 18:29 UTC, helrond commented
Looking at the script a bit more, I think using a class-based approach is overly verbose and not really helpful since we're not passing any arguments, so I converted to a simple function instead, and added a module-level docstring.

2021-02-22 18:44 UTC, merged